# Header
menu:
  Home: /
  Archives: /archives

# links with icon in the left-column bar
subnav:
  github: "https://github.com/Sonryonha"
  mail: "Sonryonha@163.com"
  # rss: "/atom.xml"
  # zhihu: "#"
  # weibo: "#"
  # douban: "#"
  # facebook: "#"
  # google: "#"
  # twitter: "#"
  # linkedin: "#"

# Set rss to false to disable feed link
# Leave rss as blank to use site's feed link, and install hexo-generate-feed
# Set rss to specific value if you have burned your feed already
rss: /atom.xml

# you can modify the value of excerpt_link to whatever you like
excerpt_link: learn more
fancybox: true
mathjax: false

# enable the animation effect, recommended
animate: true

# whether to open the link in the new window
open_in_new: true

favicon: /img/favicon.ico

# your avatar's url
avatar: /img/myself.png

# NetEase Cloud Music (wangyiyun of course)
music:
  enable: true
  # id of a certain music on NetEase Cloud Music
  id: 1903040399

# if you need to enable disqus, set 'disqus_shortname' to your disqus username
# disqus_shortname:

# whether to enable tagcloud
tagcloud: true

# whether to enable leancloud to count visitors
leancloud_visitors:
  enable: false
  app_id: your_app_id
  app_key: your_app_key

# whether to enable the friend links, if not, set 'friends' to false and do not add any link
# friends: false
friends:
  github: https://github.com/
# a brief introduction to yourself
aboutme: New developer.
